# Generated by Django 4.2.2 on 2023-06-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='orderdate',
            field=models.DateField(null=True),
        ),
    ]
