# Generated by Django 4.2.2 on 2023-06-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalTrack', '0002_alter_consumer_dob_alter_meal_orderdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_type',
            name='calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='CalTrack.meal_time'),
        ),
    ]
