# Generated by Django 4.2.2 on 2023-06-15 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalTrack', '0003_food_type_calories_alter_meal_meal_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_type',
            name='calories',
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='CalTrack.food_type'),
        ),
    ]
