# Generated by Django 4.2.2 on 2023-06-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalTrack', '0004_remove_food_type_calories_food_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
